### ISSUE TITLE
Import existing data and database

### ISSUE THREAD

**Issue by vedrancek** [mhubig/docker-partkeepr#35]
Hello,

I have an existing partkeepr database on a different server, which is not dockerized. Now I want to migrate to a new server employing partkeepr in a docker. I have successfully installed your image and it is up and running. Now I would like to move the data from the old server/database to this (new, dockerized).
I have backed up the data from the data folder and made a backup dump of the database (MariaDB). I had no problem copying the data folder files to the docker volume, but I am stuck with importing the SQL dump into the database.
My procedure for importing the dumped database is:
1. copy the  SQL dump file from the local directory to the mariadb container: docker cp base_dump.sql partkeepr_database_1:/home
2. execute themariadb-container using: docker exec -it -u root partkeepr_database_1 bash
3. import this SQL dump file: mysql partkkepr < /home/base_dump.sql

When executing the last command I get the following error: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

My docker-compose.yml looks like this: 
```
version: "3"
services:

  database:
    image: mariadb:10.0
    restart: on-failure
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=no
      - MYSQL_ROOT_PASSWORD=myrootpass
      - MYSQL_DATABASE=partkeepr
      - MYSQL_USER=partkeepr
      - MYSQL_PASSWORD=partkeepr
    volumes:
      - mysql-data:/var/lib/mysql

  partkeepr:
    image: mhubig/partkeepr:latest
    restart: on-failure
    environment:
      - PARTKEEPR_DATABASE_HOST
      - PARTKEEPR_DATABASE_NAME
      - PARTKEEPR_DATABASE_PORT
      - PARTKEEPR_DATABASE_USER
      - PARTKEEPR_DATABASE_PASS
      - PARTKEEPR_FR3D_LDAP_DRIVER_ACCOUNTCANONICALFORM
      - PARTKEEPR_FR3D_LDAP_DRIVER_ACCOUNTDOMAINNAME
      - PARTKEEPR_FR3D_LDAP_DRIVER_ACCOUNTDOMAINNAMESHORT
      - PARTKEEPR_FR3D_LDAP_DRIVER_ACCOUNTFILTERFORMAT
      - PARTKEEPR_FR3D_LDAP_DRIVER_BASEDN
      - PARTKEEPR_FR3D_LDAP_DRIVER_BINDREQUIRESDN
      - PARTKEEPR_FR3D_LDAP_DRIVER_HOST
      - PARTKEEPR_FR3D_LDAP_DRIVER_OPTREFERRALS
      - PARTKEEPR_FR3D_LDAP_DRIVER_PASSWORD
      - PARTKEEPR_FR3D_LDAP_DRIVER_PORT
      - PARTKEEPR_FR3D_LDAP_DRIVER_USESSL
      - PARTKEEPR_FR3D_LDAP_DRIVER_USESTARTTLS
      - PARTKEEPR_FR3D_LDAP_DRIVER_USERNAME
      - PARTKEEPR_FR3D_LDAP_USER_ATTRIBUTE_EMAIL
      - PARTKEEPR_FR3D_LDAP_USER_ATTRIBUTE_USERNAME
      - PARTKEEPR_FR3D_LDAP_USER_BASEDN
      - PARTKEEPR_FR3D_LDAP_USER_ENABLED
      - PARTKEEPR_FR3D_LDAP_USER_FILTER
      - PARTKEEPR_LOCALE
      - PARTKEEPR_MAILER_AUTH_MODE
      - PARTKEEPR_MAILER_ENCRYPTION
      - PARTKEEPR_MAILER_HOST
      - PARTKEEPR_MAILER_PASSWORD
      - PARTKEEPR_MAILER_PORT
      - PARTKEEPR_MAILER_TRANSPORT
      - PARTKEEPR_MAILER_USER
      - PARTKEEPR_AUTH_MAX_USERS
      - PARTKEEPR_CATEGORY_PATH_SEPARATOR
      - PARTKEEPR_CRONJOB_CHECK
      - PARTKEEPR_FILESYSTEM_DATA_DIRECTORY
      - PARTKEEPR_FILESYSTEM_QUOTA
      - PARTKEEPR_MAINTENANCE
      - PARTKEEPR_MAINTENANCE_MESSAGE
      - PARTKEEPR_MAINTENANCE_TITLE
      - PARTKEEPR_OCTOPART_APIKEY
      - PARTKEEPR_PARTS_INTERNALPARTNUMBERUNIQUE
      - PARTKEEPR_PARTS_LIMIT
      - PARTKEEPR_USERS_LIMIT
      - PARTKEEPR_SECRET
    ports:
      - "10000:80"
    volumes:
      - partkeepr-conf:/var/www/html/app/config
      - partkeepr-data:/var/www/html/data
      - partkeepr-web:/var/www/html/web
    depends_on:
      - database

  cronjob:
    image: mhubig/partkeepr:latest
    restart: on-failure
    entrypoint: []
    command: bash -c "crontab /etc/cron.d/partkeepr && cron -f"
    volumes:
      - partkeepr-conf:/var/www/html/app/config:ro
      - partkeepr-data:/var/www/html/data
      - partkeepr-web:/var/www/html/web
    depends_on:
      - partkeepr

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdmin_PartKeepr
    restart: on-failure
    links:
      - 'database:db'
    ports:
      - 10001:80

volumes:
  partkeepr-conf:
  partkeepr-data:
  partkeepr-web:
  mysql-data:
```

I have added a PHPMyAdmin service for a clearer look and possibly to import the dump from there but there is a 2 MB database dump size limit, which I think is not an issue. 
One thing that caught my eye that there is no "User Accounts" tab in PHPMyAdmin. partkeepr user seems to be added (since I can log in) but there is no root account.

Please advise, how to correctly import the old database.

Regards.
